sudo: false

language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=4.0 COVERAGE=1 GRUNT=1 WP_MULTISITE=1
  fast_finish: true

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

install:
  - npm install -g npm@latest
  - npm install -g grunt-cli
  - npm install --no-optional
  - phpenv local 5.6
  - composer self-update
  - composer install
  - phpenv local --unset

before_script:
  - wget https://raw.githubusercontent.com/wp-cli/sample-plugin/master/bin/install-wp-tests.sh
  - bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - phpenv rehash

script:
  - grunt phpunit
  - grunt phplint
  - if [[ "$GRUNT" == "1" ]]; then grunt; fi

after_success:
  - if [[ '1' == $COVERAGE ]]; then php vendor/bin/coveralls fi
